volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
  etc_wireguard:
  etc_homarr:
  etc_homarr_icons:

services:
    duckdns:
        image: ghcr.io/anujdatar/duckdns
        container_name: duckdns
        restart: unless-stopped
        environment:
          - SUBDOMAINS=${DUCK_DNS_SUBDOMAIN}
          - TOKEN=${DUCK_DNS_TOKEN}
          - TZ=${TZ}
          - FREQUENCY=5
        networks:
          vpn:
            ipv4_address: 10.9.1.2

    pihole:
        image: cbcrowe/pihole-unbound:latest
        container_name: pihole-unbound
        ports:
          - 53:53/tcp
          - 53:53/udp
          - 443:443/tcp
          - 1010:80/tcp
        environment:
          # Raspberry PI IP Address
          # Example: 192.168.50.236
          - ServerIP=${RASPBERRY_PI_IP_ADDRESS}

          # ⚠️ Change the Web UI Password:
          - WEBPASSWORD=${DEFAULT_ADMIN_PASSWORD}

          - TZ=${TZ}
          - DNSSEC=true
          - DNS1=127.0.0.1#5335 # Hardcoded to our Unbound server
          - DNS2=127.0.0.1#5335 # Hardcoded to our Unbound server
          - DNSMASQ_LISTENING=all
        volumes:
          - etc_pihole-unbound:/etc/pihole:rw
          - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
        restart: unless-stopped
        networks:
          vpn:
            ipv4_address: 10.9.1.3

    wg-easy:
        depends_on: [pihole, duckdns]
        image: ghcr.io/wg-easy/wg-easy
        container_name: wg-easy
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        environment:
          # ⚠ DUCK_DNS
          # Example: subdomain.duckdns.org
          - WG_HOST=$DUCK_DNS_SUBDOMAIN.duckdns.org

          # ⚠️ Change the Web UI Password:
          - PASSWORD=${DEFAULT_ADMIN_PASSWORD}

          # Clients IP address range.
          - WG_DEFAULT_ADDRESS=10.8.0.x

           # 💡 This is the Pi-Hole Container's IP Address
          - WG_DEFAULT_DNS=10.9.1.3
          - WG_PORT=51820
          - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
          - UI_TRAFFIC_STATS=true
          - UI_CHART_TYPE=1
        volumes:
          - etc_wireguard:/etc/wireguard:rw
        ports:
          - 51820:51820/udp
          - 51821:51821/tcp
        sysctls:
          - net.ipv4.ip_forward=1
          - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        networks:
          vpn:
            ipv4_address: 10.9.1.4

    homarr:
        image: ghcr.io/ajnart/homarr:latest
        container_name: homarr
        ports:
          - 7575:7575/tcp
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=${TZ}
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - etc_homarr:/app/data/configs
          - etc_homarr_icons:/app/public/icons
        restart: unless-stopped
        networks:
            vpn:
              ipv4_address: 10.9.1.5

    dash:
      image: mauricenino/dashdot:sha-2356692
      container_name: dashdot
      privileged: true
      ports:
        - 3001:3001
      volumes:
        - /:/mnt/host:ro
      restart: unless-stopped
      networks:
            vpn:
              ipv4_address: 10.9.1.6

networks:
  vpn:
    ipam:
      config:
        - subnet: 10.9.1.0/24