volumes:
  etc_languagetool:
  etc_changedetection:
  etc_gotify:

services:
    languagetool:
      image: silviof/docker-languagetool
      container_name: languagetool
      privileged: true
      read_only: true
      ports:
        - 8010:8010
      volumes:
        - etc_languagetool:/languagetool/tmp
        #- ./data/ngrams:/ngrams
      restart: unless-stopped
      networks:
        utility:
          ipv4_address: 10.12.1.2

    changedetection:
        image: dgtlmoon/changedetection.io:latest
        container_name: changedetection.io
        restart: unless-stopped
        ports:
          - 5000:5000
        volumes:
          - etc_changedetection:/datastore
        networks:
          utility:
            ipv4_address: 10.12.1.3

    gotify:
        image: ghcr.io/gotify/server-arm7
        container_name: gotify
        restart: unless-stopped
        ports:
          - 5001:80
        environment:
          - TZ=${TZ}
        volumes:
          - etc_gotify:/app/data
        networks:
          utility:
            ipv4_address: 10.12.1.4

networks:
  utility:
    ipam:
      config:
        - subnet: 10.12.1.0/24