volumes:
  etc_languagetool:
  etc_changedetection:

services:
  languagetool:
      image: silviof/docker-languagetool
      container_name: languagetool
      privileged: true
      read_only: true
      ports:
        - 8010:8010
      volumes:
        - etc_languagetool:/languagetool/tmp
        - ./data/ngrams:/ngrams
      restart: unless-stopped
      networks:
        util:
          ipv4_address: 10.12.1.2

  changedetection:
      image: dgtlmoon/changedetection.io:latest
      container_name: changedetection.io
      restart: unless-stopped
      ports:
        - 5000:5000
      volumes:
        - etc_changedetection:/datastore
      networks:
        util:
          ipv4_address: 10.12.1.3

networks:
  util:
    ipam:
      config:
        - subnet: 10.12.1.0/24