services:
    homeassistant:
        image: homeassistant/home-assistant:stable
        container_name: homeassistant
        restart: unless-stopped
        ports:
          - 8123:8123/tcp
        environment:
          - TZ=America/New_York
        volumes:
          - /srv/ha_config:/config
          - /etc/localtime:/etc/localtime:ro
          - /run/dbus:/run/dbus:ro # Check your Raspberry Pi for this. It could be different.
        privileged: true
        devices:
          - /dev/ttyAMA0:/dev/ttyAMA0 # Check your Raspberry Pi /dev/ to see what bluetooth device you have.
        network_mode: host